# Server configuration
server:
  port: 8088
  contextPath:

# Spring configuration
spring:
  redis:
    database: 0
    host: 10.0.0.16
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 5000


# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

#spring.boot.admin.url: http://localhost:8080
